### ISSUE TITLE
I need your help to understand adapting typescript.

### ISSUE THREAD

**Issue by Seolhun** [alexjoverm/Vue-Typescript-Starter#10]
I saw your code and help me many things.
but, I don't understand exactly. Your vue don't have ts code and Decorators never.
just use lang="ts".
Please, more information to add ts code in vue.
I'm in config problem.

**Comment by alexjoverm** [comment]
Hi @Seolhun,

This is just a starter, with this config you can start adding your typescript code, decorators or whatever. If you wanna get deeper on that, I recorded the course [Use TypeScript to Develop Vue.js Web Applications](https://egghead.io/courses/use-typescript-to-develop-vue-js-web-applications)
