### ISSUE TITLE
TS2345error on vue-router

### ISSUE THREAD

**Issue by gring2** [alexjoverm/Vue-Typescript-Starter#3]
i cloned the repository following egghead.io
but my code make TS2345 error on vue-router in /src/router/index.ts
however still no problem with build.
i think it is maybe about typescript typing problem. 

> Error:(8, 27) TS2345:Argument of type '{ routes: { path: string; name: string; component: "string" | "number" | "boolean" | "symbol" | "...' is not assignable to parameter of type 'RouterOptions'.
  Types of property 'routes' are incompatible.
    Type '{ path: string; name: string; component: "string" | "number" | "boolean" | "symbol" | "undefined"...' is not assignable to type 'RouteConfig[]'.
      Type '{ path: string; name: string; component: "string" | "number" | "boolean" | "symbol" | "undefined"...' is not assignable to type 'RouteConfig'.
        Types of property 'component' are incompatible.
          Type '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"' is not assignable to type 'Component'.
            Type '"string"' is not assignable to type 'Component'.

`
import Vue, { ComponentOptions } from 'vue'
import Router from 'vue-router'
import Hello from '@/components/Hello.vue'
import HelloTS from '@/components/HelloTS.vue'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: Hello
    },
    {
      path: '/hello-ts',
      name: 'HelloTS',
      component: HelloTS
    }
  ]
})

`

> Solve
i delete "typeof" word from "vue-shim.d.ts" file

**Comment by samuba** [comment]
This Issue has been closed without getting fixed in the code for some reason. I will do a PR.
