### ISSUE TITLE
TS2307Error on  "import App from './App' with Webstorm

### ISSUE THREAD

**Issue by gring2** [alexjoverm/Vue-Typescript-Starter#4]
i cloned repo and i open it with WebStorm but my tsc make TS2307 error unlike the video

do you have any idea how can i deal with this problem to make this error disappear on my WebStorm?

> Error:(5, 17) TS2307:Cannot find module './App'.

`import './hooks'
import Vue from 'vue'
import App from './App'
import router from './router'

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
`

**Comment by alexjoverm** [comment]
Sorry, the issue is not related to this project
