### ISSUE TITLE
Editor (vscode) keeps yelling at the line import App from './App'

### ISSUE THREAD

**Issue by sosoriov** [alexjoverm/Vue-Typescript-Starter#6]
Hi @alexjoverm 

You have done an excellent job here! thanks man.

I have small issue trying to use *TS* and *Vue*. I have followed your instructions in your post (https://alexjoverm.github.io/2017/06/28/Integrate-TypeScript-in-your-Vue-project/) and also cloning this repo both with same result.

The problem is in the *main.ts* file:
the compiler says:
`[ts] Cannot find module './App'. (4, 17)`

line:
`import App from './App'`

I've tried different settings without success, but if you add the *vue* extension to the import it works.
`import App from './App.vue'`

any idea?

My TS version is 2.5.2

**Comment by alexjoverm** [comment]
It seems is an issue on the vetur plugin side, but it [doesn't seem its expected to be fixed](https://github.com/vuejs/vetur/issues/423#issuecomment-330190365). I've pushed a commit adding the `.vue` extension to the `main.ts` file though.

**Comment by HerringtonDarkholme** [comment]
I believe that ts-loader cannot handle vue file without proper extension. It's not an editor issue.
